services:
  api:
    container_name: nome-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      -  4652:8080
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on: ["livros-api-sql"]
    networks:
      livros-network:
  

  livros-api-sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SenhaForte123"
    volumes:
      - "livros-api-mssql-azure-edge:/var/opt/mssql"
    networks:
      livros-network:
        aliases:
          - "sql" 
  

volumes:
  livros-api-mssql-azure-edge:
    

networks:
  livros-network:
    driver: bridge
 

   // terminal: docker compose --project-name livros up -d